version: '{build}'
os: Visual Studio 2015
platform: x64

install:
  - ps: >
      Invoke-WebRequest "http://beta.unity3d.com/download/d44b7ab76b45/Windows64EditorInstaller/UnitySetup64-5.5.0f1.exe" -OutFile .\UnitySetup64.exe

      (Get-Item .\UnitySetup64.exe).length

      date

      Start-Process -FilePath ".\UnitySetup64.exe" -Wait -ArgumentList ('/S', '/Q')

      date

      Invoke-WebRequest "https://bitbucket.org/Unity-Technologies/unitytesttools/get/5.5.zip"  -OutFile .\UnityTestTools.zip

      (Get-Item .\UnityTestTools.zip).length

      Expand-Archive .\UnityTestTools.zip .

      Move-Item Unity-Technologies-unitytesttools-*\Assets\UnityTestTools C:\projects\unity-platformer\Assets\UnityTestTools

build: off

test_script:
  - ps: >
      $env:Path += ";C:\Program Files\Unity\Editor"

      date

      Start-Process -FilePath "Unity.exe" -Wait -ArgumentList ('-batchmode', '-nographics', '-projectPath', 'C:\projects\unity-platformer', '-runEditorTests', '-editorTestsResultFile', 'C:\projects\unity-platformer\unit-test-results.xml', '-editorTestsFilter', 'UnityPlatformer', '-logFile', 'C:\projects\unity-platformer\log-unit-test.txt', '-quit', '-force-free')

      date

      Start-Sleep -s 1

      Get-Content C:\projects\unity-platformer\log-unit-test.txt

      Get-Content C:\projects\unity-platformer\unit-test-results.xml

      $wc = New-Object 'System.Net.WebClient'

      $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", "C:\projects\unity-platformer\unit-test-results.xml")

deploy: off

#cache:
#  - C:\Program Files\Unity\ -> appveyor.yml
