version: '{build}'
os: Visual Studio 2015
platform: x64
# Invoke-WebRequest "http://beta.unity3d.com/download/d44b7ab76b45/Windows64EditorInstaller/UnitySetup64-5.5.0f1.exe" -OutFile .\UnitySetup64.exe
# Invoke-WebRequest "https://bitbucket.org/Unity-Technologies/unitytesttools/get/5.5.zip"  -OutFile .\UnityTestTools.zip

install:
  - ps: >
      iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))

build:
  - ps: >
      Invoke-WebRequest "http://netstorage.unity3d.com/unity/01f4c123905a/Windows64EditorInstaller/UnitySetup64-5.4.3f1.exe" -OutFile .\UnitySetup64.exe

      Start-Process -FilePath ".\UnitySetup64.exe" -Wait -ArgumentList ('/S', '/Q')

      Invoke-WebRequest "http://ahkscript.org/download/ahk-install.exe" -OutFile .\ahk-installer.exe

      Start-Process -FilePath ".\ahk-installer.exe" -Wait -ArgumentList ('/S')

      Invoke-WebRequest "https://bitbucket.org/Unity-Technologies/unitytesttools/get/5.3.zip"  -OutFile .\UnityTestTools.zip

      (Get-Item .\UnityTestTools.zip).length

      Expand-Archive .\UnityTestTools.zip .

      Move-Item Unity-Technologies-unitytesttools-*\Assets\UnityTestTools C:\projects\unity-platformer\Assets\UnityTestTools

      $password = $env:UNITY_PASSWORD

      $password = $password -split ''

      $pass_commands = "Send, {" + ($password[1..($password.Length-2)] -join "}`nSleep, 100`nSend, {") + "}`n"

      $username = $env:UNITY_USERNAME

      $username = $username -split ''

      $user_commands = "Send, {" + ($username[1..($username.Length-2)] -join "}`nSleep, 100`nSend, {") + "}`n"

      (Get-Content C:\projects\unity-platformer\Scripts\unity.ahk).replace('; username', $user_commands).replace('; password', $pass_commands) | Set-Content C:\projects\unity-platformer\unity.ahk

      $env:Path += ";C:\Program Files\AutoHotkey"

      Start-Process -FilePath "AutoHotkey.exe" -Wait -ArgumentList ('C:\projects\unity-platformer\unity.ahk')

test_script:
  - ps: >
      $env:Path += ";C:\Program Files\Unity\Editor"

      Start-Process -FilePath "Unity.exe" -Wait -ArgumentList ('-batchmode', '-nographics', '-projectPath', 'C:\projects\unity-platformer', '-runEditorTests', '-editorTestsResultFile', 'C:\projects\unity-platformer\unit-test-results.xml', '-editorTestsFilter', 'UnityPlatformer', '-logFile', 'C:\projects\unity-platformer\log-unit-test.txt', '-quit')

      Get-Content C:\projects\unity-platformer\log-unit-test.txt

      Get-Content C:\projects\unity-platformer\unit-test-results.xml

      $wc = New-Object 'System.Net.WebClient'

      $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", "C:\projects\unity-platformer\unit-test-results.xml")

# screenshots
#on_finish:
#  - ps: Push-AppveyorArtifact

deploy: off

environment:
  UNITY_USERNAME:
    secure: ZhLFHmOtbEY+OR2B1RZTT/O4hoyCPZcyYbINwRg9WQY=
  UNITY_PASSWORD:
    secure: C+GziLnSW/7+WeChq9DTDw==
#cache:
#  - C:\Program Files\Unity\ -> appveyor.yml
